{{- if and .Values.persistence.enabled (ne .Values.persistence.type "hostPath") (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "twg.fullname" . }}
  labels:
    {{- include "twg.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml (default (list "ReadWriteOnce") .Values.persistence.accessModes) | nindent 4 }}
  resources:
    requests:
      storage: {{ required "persistence.size must be set when using PVC" .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
